adabot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 30


  # Velocity Controllers ---------------------------------------
  front_left_wheel_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: front_left_wheel_joint
    pid: {p: 1.5, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_right_wheel_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: front_right_wheel_joint
    pid: {p: 1.5, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_left_wheel_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: rear_left_wheel_joint
    pid: {p: 1.5, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_right_wheel_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: rear_right_wheel_joint
    pid: {p: 1.5, i: 0.0, d: 0.0, i_clamp: 0.0}

  # Front Left Wheel Weg Controllers ---------------------------
  front_left_weg_1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_weg_1_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_left_weg_2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_weg_2_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_left_weg_3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_weg_3_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_left_weg_4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_weg_4_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_left_weg_5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_weg_5_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_left_weg_6_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_weg_6_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_left_weg_7_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_weg_7_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_left_weg_8_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_weg_8_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_left_weg_9_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_weg_9_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}

  # Front Right Wheel Weg Controllers ---------------------------
  front_right_weg_1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_weg_1_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_right_weg_2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_weg_2_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_right_weg_3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_weg_3_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_right_weg_4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_weg_4_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_right_weg_5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_weg_5_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_right_weg_6_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_weg_6_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_right_weg_7_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_weg_7_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_right_weg_8_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_weg_8_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  front_right_weg_9_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_weg_9_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}

  # Rear Left Wheel Weg Controllers ---------------------------
  rear_left_weg_1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_left_weg_1_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_left_weg_2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_left_weg_2_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_left_weg_3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_left_weg_3_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_left_weg_4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_left_weg_4_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_left_weg_5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_left_weg_5_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_left_weg_6_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_left_weg_6_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_left_weg_7_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_left_weg_7_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_left_weg_8_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_left_weg_8_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_left_weg_9_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_left_weg_9_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}

  # Rear Right Wheel Weg Controllers ---------------------------
  rear_right_weg_1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_right_weg_1_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_right_weg_2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_right_weg_2_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_right_weg_3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_right_weg_3_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_right_weg_4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_right_weg_4_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_right_weg_5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_right_weg_5_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_right_weg_6_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_right_weg_6_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_right_weg_7_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_right_weg_7_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_right_weg_8_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_right_weg_8_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  rear_right_weg_9_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_right_weg_9_joint
    pid: {p: 500.0, i: 0.0, d: 0.0, i_clamp: 0.0}
